Repository Ducktrio/columbus-app, pull requests merged in 2025-07, with the labels that each got.

#6 Models initiation
  app/Models/Customer.php
  app/Models/Role.php
  app/Models/Room.php
  app/Models/RoomTicket.php
  app/Models/RoomType.php
  app/Models/Service.php
  app/Models/ServiceTicket.php
  app/Models/User.php
Labels: enhancement

#7 Added database migrations, seeder, and model specific methods
  app/Models/RoomTicket.php
  app/Models/ServiceTicket.php
  app/Models/User.php
  database/migrations/0001_01_01_000000_create_users_table.php
  database/migrations/2025_07_03_231310_initial_migration.php
  database/seeders/DatabaseSeeder.php
Labels: enhancement

#14 Bootstrap and login page
  package-lock.json
  package.json
  resources/css/app.css
  resources/js/app.js
  resources/views/auth/login.blade.php
  resources/views/components/footer.blade.php
  resources/views/components/navbar.blade.php
  resources/views/layouts/base.blade.php
  routes/web.php
Labels: enhancement

#18 Manager's panel for managing Rooms and Users
  app/Http/Controllers/AuthController.php
  app/Http/Controllers/RoomsController.php
  app/Http/Controllers/UsersController.php
  app/Http/Middleware/RoleRedirector.php
  app/Http/Requests/CreateRoomRequest.php
  app/Http/Requests/CreateUserRequest.php
  package-lock.json
  package.json
  resources/js/app.js
  resources/views/auth/login.blade.php
  resources/views/components/toast.blade.php
  resources/views/index.blade.php
  resources/views/layouts/base.blade.php
  resources/views/managers/base.blade.php
  resources/views/managers/createUser.blade.php
  resources/views/managers/room/createRoom.blade.php
  resources/views/managers/room/manageRooms.blade.php
  resources/views/managers/room/roomDetail.blade.php
  resources/views/managers/user/createUser.blade.php
  resources/views/managers/user/listUsers.blade.php
  resources/views/receptionist/base.blade.php
  resources/views/receptionist/dashboard.blade.php
  routes/web.php
Labels: enhancement

#21 Created Middleware
  app/Http/Controllers/RoomsController.php
  app/Http/Middleware/RolesMiddleware.php
Labels: enhancement

#23 Staff's panel, set tickets
  app/Http/Controllers/RoomsController.php
  app/Http/Controllers/ServiceTicketsController.php
  app/Http/Middleware/RoleRedirector.php
  app/Http/Middleware/RolesMiddleware.php
  app/Http/Requests/CreateServiceTicketRequest.php
  bootstrap/app.php
  config/app.php
  database/seeders/DatabaseSeeder.php
  resources/views/components/ticket.blade.php
  resources/views/components/toast.blade.php
  resources/views/index.blade.php
  resources/views/managers/base.blade.php
  resources/views/managers/partials/customerList.blade.php
  resources/views/managers/partials/roomList.blade.php
  resources/views/managers/room/createRoom.blade.php
  resources/views/managers/room/manageRooms.blade.php
  resources/views/managers/ticket/createTicket.blade.php
  resources/views/managers/user/createUser.blade.php
  resources/views/managers/user/listUsers.blade.php
  resources/views/staff/base.blade.php
  resources/views/staff/dashboard.blade.php
  resources/views/staff/sidebar.blade.php
  resources/views/staff/ticketDetail.blade.php
  routes/web.php
Labels: enhancement

#28 UI for Receptionist
  app/Http/Controllers/CustomersController.php
  app/Http/Controllers/RoomTicketsController.php
  app/Http/Controllers/RoomsController.php
  app/Http/Controllers/ServiceTicketsController.php
  app/Http/Requests/CreateCustomerRequest.php
  app/Http/Requests/CreateRoomTicketRequest.php
  app/Models/RoomTicket.php
  database/migrations/2025_07_03_231310_initial_migration.php
  database/seeders/DatabaseSeeder.php
  resources/views/components/room.blade.php
  resources/views/layouts/base.blade.php
  resources/views/managers/partials/roomList.blade.php
  resources/views/managers/room/manageRooms.blade.php
  resources/views/receptionist/base.blade.php
  resources/views/receptionist/checkDetail.blade.php
  resources/views/receptionist/checkin.blade.php
  resources/views/receptionist/checkout.blade.php
  resources/views/receptionist/checks.blade.php
  resources/views/receptionist/customer.blade.php
  resources/views/receptionist/customer/list.blade.php
  resources/views/receptionist/customer/register.blade.php
  resources/views/receptionist/dashboard.blade.php
  resources/views/receptionist/partials/checkList.blade.php
  resources/views/receptionist/partials/customerList.blade.php
  resources/views/receptionist/partials/roomList.blade.php
  resources/views/receptionist/rooms/roomDetail.blade.php
  resources/views/receptionist/rooms/roomList.blade.php
  resources/views/receptionist/tickets/createTicket.blade.php
  resources/views/receptionist/tickets/manageTickets.blade.php
  resources/views/receptionist/tickets/ticketDetail.blade.php
  routes/web.php
Labels: enhancement

#34 Deploy 1.0.1
  Dockerfile
  docker/start.sh
  resources/views/auth/login.blade.php
Labels: enhancement

#39 Toast fix
  Dockerfile
  resources/views/components/toast.blade.php
  resources/views/receptionist/base.blade.php
  routes/web.php
Labels: bug

#42 Add tickets count label on Staff panel.
  resources/views/staff/dashboard.blade.php
Labels: enhancement

#47 Removed Unsused Validation Text
  resources/views/receptionist/customer/register.blade.php
Labels: invalid
